[package]
name = "rmonkey"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.60", features = ["derive"] }
log = "0.4.29"
thiserror = "2.0.18"

[lints.clippy]
uninlined_format_args = "allow"
